"""Export review-sized results without deleting any raw evidence."""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent
r=HERE/'results'
raw=json.loads((r/'independent_v2.json').read_text())
modal=json.loads((r/'modal_certificate.json').read_text())
readout=json.loads((r/'readout_certificate.json').read_text())
diag=json.loads((r/'mechanism_diagnostics.json').read_text())
finite=json.loads((r/'finite_pair.json').read_text())
windows=json.loads((r/'finite_windows.json').read_text())
files=['modal_certificate.json','readout_certificate.json','independent_v2.json','mechanism_diagnostics.json','finite_pair.json','finite_windows.json','tests.log']
summary={
 'scope':'V2 research evidence, not TAP-ready, not a new adaptive method',
 'registered_base':'418ef53a7d7d2f79d6228d023baf8b101e3b3e2e',
 'registered_branch':'research/q5-certified-windows-v2',
 'submission_branch':'research/q5-readout-verification-v2',
 'modal':{k:v for k,v in modal.items() if k!='boxes'},
 'readout':readout,
 'independent':{k:v for k,v in raw.items() if k!='rows'},
 'counts':{k:sum(row['methods'][k]['task_success'] for row in raw['rows']) for k in raw['rows'][0]['methods']},
 'all_scene_results':[{k:v for k,v in row.items() if k not in ('noise_free_all_fields','observed_all_fields')} for row in raw['rows']],
 'oracle_counts':diag['counts'],
 'tangent_discrepancy_fractions':[row['local_tangent_model_error_fraction'] for row in diag['rows']],
 'finite_pair_diagnostics':finite,
 'finite_window_certificate':windows,
 'raw_evidence_sha256':{f:hashlib.sha256((r/f).read_bytes()).hexdigest() for f in files},
 'availability':'Full raw arrays and 5500 interval rows are in the accompanying archive or generated by the scripts. They are not claimed to be embedded in this compact file.'}
(r/'SUMMARY.json').write_text(json.dumps(summary,indent=2)+'\n')
small={k:v for k,v in summary.items() if k not in ('all_scene_results','tangent_discrepancy_fractions')}
small['scene_material_errors']=[{'scene':row['scene'],'truth':row['truth'],
 'methods':{k:{'errors':v['material_errors'],'success':v['task_success']} for k,v in row['methods'].items()}} for row in raw['rows']]
(r/'REVIEW.json').write_text(json.dumps(small,indent=2)+'\n')
print(json.dumps({'counts':summary['counts'],'raw_evidence_sha256':summary['raw_evidence_sha256']},indent=2))
